import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import ButtonPrimary from "../components/buttonprimary";
import ButtonOutline from "../components/buttonoutline";
import ButtonArrow from "../components/buttonarrow";
import ButtonSecondary from "../components/buttonsecondary";
import ButtonLink from "../components/buttonlink";
import Footer from "../components/footer/footer";

export default function Home() {
  return (
    <div className="overflow-hidden antialiased">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen w-full bg-[#fff]">
        <Navbar />
        <section className="py-20 flex flex-col h-full w-full">
          <ButtonPrimary href="#" />
          <ButtonOutline href="#" />
          <ButtonArrow />
          <ButtonSecondary href="#" />
          <ButtonLink href="#" />
          <Footer />
        </section>
      </main>
    </div>
  );
}
