import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import LinkBtnPrimary from "../components/linkbtnprimary";
import BtnPrimary from "../components/btnprimary";
import LinkBtnOutline from "../components/linkbtnoutline";
import ButtonSecondary from "../components/linkbtnsecondary";
import LinkText from "../components/linktext";
import Footer from "../components/footer/footer";
import HomeBanner from "../components/section/home/homebanner";
import NewsSection from "../components/section/home/newssection";
import ProfilePerusahaan from "../components/banner/profileperusahaan";
import KonsultasiKeuanganSection from "../components/section/konsultasikeuangansection";

export default function Home() {
  return (
    <div className="overflow-hidden antialiased">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen w-full bg-[#005eeead]">
        <Navbar />
        <section className="py-20 flex flex-col h-full w-full">
          <div className="flex py-40">
            <LinkBtnPrimary href="#">Link Btn Primary</LinkBtnPrimary>
            <LinkBtnOutline href="#">Link Btn Outline</LinkBtnOutline>
            <ButtonSecondary href="#">Button Secondary</ButtonSecondary>
            <BtnPrimary onClick={() => console.log("hai")}>
              Button Primary
            </BtnPrimary>
            <LinkText href="#">Link Text</LinkText>
          </div>
          <HomeBanner />
          <NewsSection />
          <ProfilePerusahaan />
          <KonsultasiKeuanganSection />
          <Footer />
        </section>
      </main>
    </div>
  );
}
